// Copyright RedFront1941. All Rights Reserved.

#include "Data/RFDataTableLoader.h"

#include "Engine/DataTable.h"
#include "HAL/FileManager.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"

namespace
{
	/**
	 * Copies rows into a transient UDataTable.
	 * The row map is rebuilt on every call so the table identity is stable and callers
	 * holding the old table continue to see valid (if replaced) data rather than a
	 * dangling pointer.
	 */
	template <typename RowType>
	void FillTable(UDataTable* Table, const TMap<FName, RowType>& Rows)
	{
		if (Table == nullptr)
		{
			return;
		}

		Table->EmptyTable();
		for (const TPair<FName, RowType>& Pair : Rows)
		{
			// AddRow copies the struct, so the row does not need to outlive this call.
			Table->AddRow(Pair.Key, static_cast<const RowType&>(Pair.Value));
		}
	}

	/** Reads the object-array field of a contract file, skipping non-object entries. */
	void ReadObjectArray(const TSharedPtr<FJsonObject>& Root, const TCHAR* Field, TArray<TSharedPtr<FJsonObject>>& Out)
	{
		Out.Reset();
		if (!Root.IsValid())
		{
			return;
		}

		const TArray<TSharedPtr<FJsonValue>>* Array = nullptr;
		if (!Root->TryGetArrayField(Field, Array) || Array == nullptr)
		{
			return;
		}

		for (const TSharedPtr<FJsonValue>& Entry : *Array)
		{
			if (Entry.IsValid() && Entry->Type == EJson::Object)
			{
				Out.Add(Entry->AsObject());
			}
		}
	}
}

FString URFDataTableLoader::GetContractFolder() const
{
	// Runtime JSON path: Content/RedFront/Data (see the header for the shipping pipeline).
	return FPaths::ConvertRelativePathToFull(FPaths::ProjectContentDir() / TEXT("RedFront/Data"));
}

FString URFDataTableLoader::GetGeneratedCsvFolder() const
{
	// The CSVs generated by tools/ land outside the project, in the shared data folder:
	// <repo>/data/generated, i.e. ProjectDir/../data/generated. The editor importer
	// (Tools > Import DataTable) is pointed at that folder.
	return FPaths::ConvertRelativePathToFull(FPaths::ProjectDir() / TEXT("../data/generated/"));
}

bool URFDataTableLoader::LoadJsonFile(const FString& FileName, TSharedPtr<FJsonObject>& OutRoot) const
{
	const FString FullPath = GetContractFolder() / FileName;

	FString RawText;
	if (!FFileHelper::LoadFileToString(RawText, *FullPath))
	{
		// A missing contract is not fatal: the game runs with the C++ defaults baked into
		// the components (weight bands, CP rules, difficulty scaling).
		UE_LOG(LogTemp, Warning, TEXT("RFDataTableLoader: contract '%s' not found at %s."), *FileName, *FullPath);
		return false;
	}

	const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(RawText);
	return FJsonSerializer::Deserialize(Reader, OutRoot) && OutRoot.IsValid();
}

bool URFDataTableLoader::LoadAllContracts()
{
	// Order matters only for the log; each builder is independent and safe to fail.
	const bool bWeapons = BuildWeaponTable();
	const bool bClasses = BuildClassTable();
	const bool bItems = BuildItemTable();
	const bool bEnemies = BuildEnemyTable();
	const bool bVehicles = BuildVehicleTable();
	const bool bAir = BuildAirUnitTable();
	const bool bSupport = BuildSupportTables();
	const bool bCampaigns = BuildCampaignTables();
	const bool bLevels = BuildLevelTables();

	UE_LOG(LogTemp, Log, TEXT("RFDataTableLoader: weapons=%d classes=%d items=%d enemies=%d vehicles=%d air=%d support=%d campaigns=%d levels=%d"),
		bWeapons ? Weapons.Num() : 0, bClasses ? Classes.Num() : 0, bItems ? Items.Num() : 0,
		bEnemies ? Enemies.Num() : 0, bVehicles ? Vehicles.Num() : 0, bAir ? AirUnits.Num() : 0,
		bSupport ? SupportCallIns.Num() : 0, bCampaigns ? Campaigns.Num() : 0, bLevels ? Levels.Num() : 0);

	return bWeapons && bClasses && bItems && bEnemies && bVehicles && bAir &&
		bSupport && bCampaigns && bLevels;
}

bool URFDataTableLoader::BuildWeaponTable()
{
	TSharedPtr<FJsonObject> Root;
	if (!LoadJsonFile(TEXT("weapons.json"), Root))
	{
		return false;
	}

	TArray<TSharedPtr<FJsonObject>> Rows;
	ReadObjectArray(Root, TEXT("weapons"), Rows);

	Weapons.Reset();
	for (const TSharedPtr<FJsonObject>& Row : Rows)
	{
		const FRFWeaponDef Definition = FRFWeaponDef::FromJson(Row);
		if (!Definition.Id.IsNone())
		{
			Weapons.Add(Definition.Id, Definition);
		}
	}

	RebuildWeaponTable();
	return Weapons.Num() > 0;
}

void URFDataTableLoader::RebuildWeaponTable()
{
	if (WeaponTable == nullptr)
	{
		WeaponTable = NewObject<UDataTable>(this, TEXT("DT_Weapons"));
		WeaponTable->RowStruct = FRFWeaponDef::StaticStruct();
	}
	FillTable<FRFWeaponDef>(WeaponTable, Weapons);
}

bool URFDataTableLoader::BuildClassTable()
{
	TSharedPtr<FJsonObject> Root;
	if (!LoadJsonFile(TEXT("classes.json"), Root))
	{
		return false;
	}

	// weight_system: base_capacity_kg / us_capacity_kg / load_bands.
	if (const TSharedPtr<FJsonObject>* WeightSystem = RFJson::GetObject(Root, TEXT("weight_system")))
	{
		BaseCapacityKg = RFJson::Number(*WeightSystem, TEXT("base_capacity_kg"), 24.0f);
		UsCapacityKg = RFJson::Number(*WeightSystem, TEXT("us_capacity_kg"), 26.0f);

		LoadBands.Reset();
		const TArray<TSharedPtr<FJsonValue>>* Bands = nullptr;
		if ((*WeightSystem)->TryGetArrayField(TEXT("load_bands"), Bands) && Bands != nullptr)
		{
			for (const TSharedPtr<FJsonValue>& Entry : *Bands)
			{
				if (Entry.IsValid() && Entry->Type == EJson::Object)
				{
					LoadBands.Add(FRFWeightBand::FromJson(Entry->AsObject()));
				}
			}
			LoadBands.Sort([](const FRFWeightBand& A, const FRFWeightBand& B) { return A.MaxRatio < B.MaxRatio; });
		}
	}

	TArray<TSharedPtr<FJsonObject>> Rows;
	ReadObjectArray(Root, TEXT("classes"), Rows);

	Classes.Reset();
	for (const TSharedPtr<FJsonObject>& Row : Rows)
	{
		const FRFClassDef Definition = FRFClassDef::FromJson(Row);
		if (!Definition.Id.IsNone())
		{
			Classes.Add(Definition.Id, Definition);
		}
	}

	RebuildClassTable();
	return Classes.Num() > 0;
}

void URFDataTableLoader::RebuildClassTable()
{
	if (ClassTable == nullptr)
	{
		ClassTable = NewObject<UDataTable>(this, TEXT("DT_Classes"));
		ClassTable->RowStruct = FRFClassDef::StaticStruct();
	}
	FillTable<FRFClassDef>(ClassTable, Classes);
}

bool URFDataTableLoader::BuildItemTable()
{
	TSharedPtr<FJsonObject> Root;
	if (!LoadJsonFile(TEXT("equipment.json"), Root))
	{
		return false;
	}

	TArray<TSharedPtr<FJsonObject>> Rows;
	ReadObjectArray(Root, TEXT("items"), Rows);

	Items.Reset();
	for (const TSharedPtr<FJsonObject>& Row : Rows)
	{
		const FRFItemDef Definition = FRFItemDef::FromJson(Row);
		if (!Definition.Id.IsNone())
		{
			Items.Add(Definition.Id, Definition);
		}
	}

	RebuildItemTable();
	return Items.Num() > 0;
}

void URFDataTableLoader::RebuildItemTable()
{
	if (ItemTable == nullptr)
	{
		ItemTable = NewObject<UDataTable>(this, TEXT("DT_Items"));
		ItemTable->RowStruct = FRFItemDef::StaticStruct();
	}
	FillTable<FRFItemDef>(ItemTable, Items);
}

bool URFDataTableLoader::BuildEnemyTable()
{
	TSharedPtr<FJsonObject> Root;
	if (!LoadJsonFile(TEXT("enemies.json"), Root))
	{
		return false;
	}

	TArray<TSharedPtr<FJsonObject>> Rows;
	ReadObjectArray(Root, TEXT("infantry"), Rows);

	Enemies.Reset();
	for (const TSharedPtr<FJsonObject>& Row : Rows)
	{
		const FRFEnemyDef Definition = FRFEnemyDef::FromJson(Row);
		if (!Definition.Id.IsNone())
		{
			Enemies.Add(Definition.Id, Definition);
		}
	}

	RebuildEnemyTable();
	return Enemies.Num() > 0;
}

void URFDataTableLoader::RebuildEnemyTable()
{
	if (EnemyTable == nullptr)
	{
		EnemyTable = NewObject<UDataTable>(this, TEXT("DT_Enemies"));
		EnemyTable->RowStruct = FRFEnemyDef::StaticStruct();
	}
	FillTable<FRFEnemyDef>(EnemyTable, Enemies);
}

bool URFDataTableLoader::BuildVehicleTable()
{
	TSharedPtr<FJsonObject> Root;
	if (!LoadJsonFile(TEXT("enemies.json"), Root))
	{
		return false;
	}

	TArray<TSharedPtr<FJsonObject>> Rows;
	ReadObjectArray(Root, TEXT("vehicles"), Rows);

	Vehicles.Reset();
	for (const TSharedPtr<FJsonObject>& Row : Rows)
	{
		const FRFVehicleDef Definition = FRFVehicleDef::FromJson(Row);
		if (!Definition.Id.IsNone())
		{
			Vehicles.Add(Definition.Id, Definition);
		}
	}

	RebuildVehicleTable();
	return Vehicles.Num() > 0;
}

void URFDataTableLoader::RebuildVehicleTable()
{
	if (VehicleTable == nullptr)
	{
		VehicleTable = NewObject<UDataTable>(this, TEXT("DT_Vehicles"));
		VehicleTable->RowStruct = FRFVehicleDef::StaticStruct();
	}
	FillTable<FRFVehicleDef>(VehicleTable, Vehicles);
}

bool URFDataTableLoader::BuildAirUnitTable()
{
	TSharedPtr<FJsonObject> Root;
	if (!LoadJsonFile(TEXT("enemies.json"), Root))
	{
		return false;
	}

	TArray<TSharedPtr<FJsonObject>> Rows;
	ReadObjectArray(Root, TEXT("air"), Rows);

	AirUnits.Reset();
	for (const TSharedPtr<FJsonObject>& Row : Rows)
	{
		const FRFAirUnitDef Definition = FRFAirUnitDef::FromJson(Row);
		if (!Definition.Id.IsNone())
		{
			AirUnits.Add(Definition.Id, Definition);
		}
	}
	return AirUnits.Num() > 0;
}

bool URFDataTableLoader::BuildSupportTables()
{
	TSharedPtr<FJsonObject> Root;
	if (!LoadJsonFile(TEXT("support.json"), Root))
	{
		return false;
	}

	if (const TSharedPtr<FJsonObject>* CommandPoints = RFJson::GetObject(Root, TEXT("command_points")))
	{
		CommandPointRules = FRFCommandPointRules::FromJson(*CommandPoints);
	}
	if (const TSharedPtr<FJsonObject>* Comms = RFJson::GetObject(Root, TEXT("comms")))
	{
		CommsRules = FRFCommsRules::FromJson(*Comms);
	}

	TArray<TSharedPtr<FJsonObject>> Rows;
	ReadObjectArray(Root, TEXT("call_ins"), Rows);

	SupportCallIns.Reset();
	SupportCallInsById.Reset();
	for (const TSharedPtr<FJsonObject>& Row : Rows)
	{
		const FRFSupportCallInDef Definition = FRFSupportCallInDef::FromJson(Row);
		if (!Definition.Id.IsNone())
		{
			SupportCallIns.Add(Definition);
			SupportCallInsById.Add(Definition.Id, Definition);
		}
	}

	// Endless mode wave table (support.json endless_mode.wave_table).
	EndlessWaves.Reset();
	if (const TSharedPtr<FJsonObject>* Endless = RFJson::GetObject(Root, TEXT("endless_mode")))
	{
		const TArray<TSharedPtr<FJsonValue>>* Waves = nullptr;
		if ((*Endless)->TryGetArrayField(TEXT("wave_table"), Waves) && Waves != nullptr)
		{
			for (const TSharedPtr<FJsonValue>& Entry : *Waves)
			{
				if (Entry.IsValid() && Entry->Type == EJson::Object)
				{
					EndlessWaves.Add(FRFEndlessWave::FromJson(Entry->AsObject()));
				}
			}
		}
	}

	RebuildSupportTable();
	return SupportCallIns.Num() > 0;
}

void URFDataTableLoader::RebuildSupportTable()
{
	if (SupportTable == nullptr)
	{
		SupportTable = NewObject<UDataTable>(this, TEXT("DT_Support"));
		SupportTable->RowStruct = FRFSupportCallInDef::StaticStruct();
	}
	FillTable<FRFSupportCallInDef>(SupportTable, SupportCallInsById);
}

bool URFDataTableLoader::BuildCampaignTables()
{
	TSharedPtr<FJsonObject> Root;
	if (!LoadJsonFile(TEXT("campaigns.json"), Root))
	{
		return false;
	}

	TArray<TSharedPtr<FJsonObject>> Rows;
	ReadObjectArray(Root, TEXT("campaigns"), Rows);

	Campaigns.Reset();
	for (const TSharedPtr<FJsonObject>& Row : Rows)
	{
		const FRFCampaignDef Definition = FRFCampaignDef::FromJson(Row);
		if (!Definition.Id.IsNone())
		{
			Campaigns.Add(Definition.Id, Definition);
		}
	}

	// difficulty_scaling is an object keyed by tier id, not an array.
	DifficultyScaling.Reset();
	if (const TSharedPtr<FJsonObject>* Scaling = RFJson::GetObject(Root, TEXT("difficulty_scaling")))
	{
		for (const TPair<FString, TSharedPtr<FJsonValue>>& Pair : (*Scaling)->Values)
		{
			if (Pair.Value.IsValid() && Pair.Value->Type == EJson::Object)
			{
				FRFDifficultyScaling Row = FRFDifficultyScaling::FromJson(Pair.Value->AsObject());
				if (Row.Id.IsNone())
				{
					Row.Id = FName(*Pair.Key);
				}
				DifficultyScaling.Add(Row.Id, Row);
			}
		}
	}

	return Campaigns.Num() > 0;
}

bool URFDataTableLoader::BuildLevelTables()
{
	// Level files live in data/levels/*.json (Content/RedFront/Data/levels/*.json at
	// runtime); each file is one campaign slice with a "levels" array. The files are
	// authored by the data owner and may not exist yet, in which case levels stay empty
	// and the game falls back to the level ids referenced by the campaigns.
	const FString LevelFolder = GetContractFolder() / TEXT("levels");

	TArray<FString> LevelFiles;
	IFileManager::Get().FindFiles(LevelFiles, *(LevelFolder / TEXT("*.json")), true, false);

	Levels.Reset();
	for (const FString& FileName : LevelFiles)
	{
		const FString FullPath = LevelFolder / FileName;

		FString RawText;
		if (!FFileHelper::LoadFileToString(RawText, *FullPath))
		{
			continue;
		}

		TSharedPtr<FJsonObject> Root;
		const TSharedRef<TJsonReader<>> Reader = TJsonReaderFactory<>::Create(RawText);
		if (!FJsonSerializer::Deserialize(Reader, Root) || !Root.IsValid())
		{
			continue;
		}

		TArray<TSharedPtr<FJsonObject>> Rows;
		ReadObjectArray(Root, TEXT("levels"), Rows);
		for (const TSharedPtr<FJsonObject>& Row : Rows)
		{
			const FRFLevelDef Definition = FRFLevelDef::FromJson(Row);
			if (!Definition.Id.IsNone())
			{
				Levels.Add(Definition.Id, Definition);
			}
		}
	}

	return Levels.Num() > 0;
}

bool URFDataTableLoader::FindLevel(FName LevelId, FRFLevelDef& OutLevel) const
{
	if (const FRFLevelDef* Found = Levels.Find(LevelId))
	{
		OutLevel = *Found;
		return true;
	}
	return false;
}

bool URFDataTableLoader::FindWeapon(FName Id, FRFWeaponDef& Out) const
{
	if (const FRFWeaponDef* Found = Weapons.Find(Id))
	{
		Out = *Found;
		return true;
	}
	return false;
}

bool URFDataTableLoader::FindItem(FName Id, FRFItemDef& Out) const
{
	if (const FRFItemDef* Found = Items.Find(Id))
	{
		Out = *Found;
		return true;
	}
	return false;
}

bool URFDataTableLoader::FindClass(FName Id, FRFClassDef& Out) const
{
	if (const FRFClassDef* Found = Classes.Find(Id))
	{
		Out = *Found;
		return true;
	}
	return false;
}

bool URFDataTableLoader::FindEnemy(FName Id, FRFEnemyDef& Out) const
{
	if (const FRFEnemyDef* Found = Enemies.Find(Id))
	{
		Out = *Found;
		return true;
	}
	return false;
}

bool URFDataTableLoader::FindVehicle(FName Id, FRFVehicleDef& Out) const
{
	if (const FRFVehicleDef* Found = Vehicles.Find(Id))
	{
		Out = *Found;
		return true;
	}
	return false;
}

bool URFDataTableLoader::FindSupportCallIn(FName Id, FRFSupportCallInDef& Out) const
{
	if (const FRFSupportCallInDef* Found = SupportCallInsById.Find(Id))
	{
		Out = *Found;
		return true;
	}
	return false;
}
